DROP TABLE IF EXISTS consumption;
CREATE TABLE consumption
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INT        NOT NULL,
    date      DATE       NOT NULL,
    liters    INT        NOT NULL,
    type      VARCHAR(3) NOT NULL,
    price     DECIMAL    NOT NULL

);

